# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
   branches:
      only:
        - master
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - add_ssh_keys:
          fingerprints:
            - '7a:56:8e:04:2e:33:82:78:f5:54:09:2e:5f:0f:69:6e'

      - run: git config user.email "wasuwat.se@gmail.com"
      - run: git config user.name "Wasuwat Lmimsuparhat"
      - run: yarn build-prefix
      - run: yarn deploy
